/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GifFramePanel.java
 *
 * Created on Apr 26, 2011, 7:28:19 PM
 */

package gif;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class GifFramePanel extends javax.swing.JPanel {
    private Animator animator;
    private GifFrame frame;

    /** Creates new form GifFramePanel */
    public GifFramePanel(Animator animator) {
        this.animator = animator;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageScrollPane = new javax.swing.JScrollPane();
        imagePanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        preview = new javax.swing.JButton();
        loop = new javax.swing.JRadioButton();
        propertiesPanel = new javax.swing.JPanel();
        widthLabel = new javax.swing.JLabel();
        width = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        delayLabel = new javax.swing.JLabel();
        delay = new javax.swing.JTextField();

        imagePanel.setLayout(new java.awt.BorderLayout());

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePanel.add(image, java.awt.BorderLayout.CENTER);

        imageScrollPane.setViewportView(imagePanel);

        preview.setText("Preview Animation...");
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        loop.setSelected(true);
        loop.setText("Loop Continuously");

        propertiesPanel.setLayout(new java.awt.GridLayout(3, 2, 10, 0));

        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        widthLabel.setText("Width:");
        propertiesPanel.add(widthLabel);
        propertiesPanel.add(width);

        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        heightLabel.setText("Height:");
        propertiesPanel.add(heightLabel);
        propertiesPanel.add(height);

        delayLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        delayLabel.setText("Delay:");
        propertiesPanel.add(delayLabel);

        delay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                delayKeyReleased(evt);
            }
        });
        propertiesPanel.add(delay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loop)
                                .addGap(22, 22, 22))
                            .addComponent(preview))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preview))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(propertiesPanel, 0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delayKeyReleased
        if (frame != null) {
            try {
                frame.setDelay(Long.parseLong(delay.getText()));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, ex, "Exception",
                        JOptionPane.ERROR_MESSAGE);
            }
            delay.setText(Long.toString(frame.getDelay()));
        }
    }//GEN-LAST:event_delayKeyReleased

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        final JDialog d = new JDialog((JFrame) null, "Animation");

        d.add(new AnimationPanel(animator.getGifFrames(), loop()));

        JPanel p = new JPanel();

        JButton b = new JButton("OK");
        b.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                d.dispose();
            }
        });
        p.add(b);

        d.add(p, BorderLayout.SOUTH);

        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_previewActionPerformed

    public void setGifFrame(GifFrame frame) {
        this.frame = frame;
        if (frame != null) {
            image.setIcon(new ImageIcon(frame.getImage()));
            width.setText(Integer.toString(frame.getImage().getWidth()));
            height.setText(Integer.toString(frame.getImage().getHeight()));
            delay.setText(Long.toString(frame.getDelay()));
        } else {
            image.setIcon(null);
            width.setText("");
            height.setText("");
            delay.setText("");
        }
    }

    public boolean loop() {
        return loop.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delay;
    private javax.swing.JLabel delayLabel;
    private javax.swing.JLabel height;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JScrollPane imageScrollPane;
    private javax.swing.JRadioButton loop;
    private javax.swing.JButton preview;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JLabel width;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables

}
